name: surakshalens
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  image_picker: ^1.2.3
  url_launcher: ^6.3.2
  flutter_tts: ^4.2.5
  speech_to_text: ^7.5.0
  shared_preferences: ^2.5.5
  google_mlkit_text_recognition: ^0.15.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

